### ISSUE TITLE
Request: I need to be able to set a base_dir at the same time as using the `modified` strategy

### ISSUE THREAD

**Issue by rosieyohannan** [CircleCI-Public/vale-orb#10]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Describe the problem imposed by not having this feature

I have an "archived" folder in my repo. 
I am using the `modified` strategy. 
I do not want to lint files that I move to the archived folder in a branch but they are considered "modified" so are included. There is the option to set a `base_dir` and the orb docs do not specify that this is unsupported when using the "modified" strategy, but looking at the orb source it seems this is the case: Either lint all modified files, or lint all files but scope using a `base_dir`.

### Describe the solution you'd like

I would like some way to have vale "ignore" a directory while only linting modified files.

**Comment by marboledacci** [comment]
This is now part of version v1.2.0
